Update release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -136,7 +136,7 @@ jobs:
         run: |
           mkdir -p release
           cp {LICENSE,README.md,CHANGELOG.md} release/ 2> /dev/null || echo "Copy Failed...Ignoring.."
-          cp target/aarch64-unknown-linux-gnu/release/${{matrix.file_name}} release/
+          cp target/${{ matrix.target }}/release/${{matrix.file_name}} release/
 
           mv release/ ${{matrix.asset_name}}/
 
@@ -187,7 +187,9 @@ jobs:
         include:
           - os: macos-12
             target: aarch64-apple-darwin
+            file_name: dozer
             asset_name: dozer-macos-aarch64
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -198,7 +200,7 @@ jobs:
           profile: minimal
           target: ${{ matrix.target }}
           override: true
-            - name: Install Protoc
+      - name: Install Protoc
         uses: arduino/setup-protoc@v1
         with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
@@ -222,16 +224,55 @@ jobs:
         with:
           command: build
           args: --release --target ${{ matrix.target }}
-      - name: Upload the binary to release
-        # No need to upload binaries for dry run (cron)
-        if: github.event_name == 'release'
-        uses: svenstaro/upload-release-action@2.5.0
-        with:
-          repo_token: ${{ secrets.MEILI_BOT_GH_PAT }}
-          file: target/${{ matrix.target }}/release/dozer
-          asset_name: ${{ matrix.asset_name }}
-          tag: ${{ github.ref }}
+          
+      - name: List target output files
+        run: ls -lR ./target
+      
+      - name: Prepare release assets
+        shell: bash
+        run: |
+          mkdir -p release
+          cp {LICENSE,README.md,CHANGELOG.md} release/ 2> /dev/null || echo "Copy Failed...Ignoring.."
+          cp target/${{ matrix.target }}/release/${{matrix.file_name}} release/
 
+          mv release/ ${{matrix.asset_name}}/
+
+          tar -czvf ${{matrix.asset_name}}.tar.gz ${{matrix.asset_name}}/
+
+      - name: Upload the release
+        uses: svenstaro/upload-release-action@v2
+        with:
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          file: ${{matrix.asset_name}}*
+          file_glob: true
+          overwrite: true
+          tag: ${{ needs.prepare.outputs.version }}
+          release_name: "Development Release - ${{ needs.prepare.outputs.version }}"
+          prerelease: ${{ needs.prepare.outputs.prerelease }}
+          body: "${{ needs.prepare.outputs.release_body }}"
+      
+      - name: Set env variables
+        env: 
+          VERSION: ${{ needs.prepare.outputs.version }}
+          RELEASE_NAME: ${{matrix.asset_name}}.tar.gz
+        run: |
+          echo "RELEASE_NAME=${{env.RELEASE_NAME}}" >> $GITHUB_ENV
+          echo "VERSION=${{env.VERSION}}" >> $GITHUB_ENV
+          echo "ARTIFACT_URL=https://${{ env.BUCKET_NAME }}.s3.ap-southeast-1.amazonaws.com/${{ env.VERSION }}/${{ env.RELEASE_NAME }}" >> $GITHUB_ENV
+
+      - name: configure aws credentials
+        if: matrix.os == 'ubuntu-20-16-cores'
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+          role-session-name: deployer
+          aws-region: ap-southeast-1
+
+      - name: Upload release to S3
+        id: upload_s3
+        if: matrix.os == 'ubuntu-20-16-cores'
+        run: |
+          aws s3 cp $RELEASE_NAME s3://${{ env.BUCKET_NAME }}/$VERSION/$RELEASE_NAME
   release:
     name: Release
     runs-on: 
